version: '3.8'

services:
  nginx:
    image: nginx:1.27-alpine-slim
    ports:
      - "1337:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/usr/src/app
    depends_on:
      - api
  api:
    build: ./app/
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./app/:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
volumes:
  postgres_data:
  static_volume:
  media_volume:
