# Generated by Django 5.0.6 on 2024-06-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('phones', '0004_rename_call_outgoing_sec_sec_limits_from_phonelimit_call_outgoing_sec_limits_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название команды')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'commands',
            },
        ),
        migrations.CreateModel(
            name='CommandArg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название атрибута команды')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.command')),
            ],
            options={
                'verbose_name': 'Атрибуты команды',
                'verbose_name_plural': 'Атрибуты команд',
                'db_table': 'commands_args',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('OFF', 'Выключен'), ('ON', 'Включен'), ('PROGRESS', 'Исполняет команду')],
                                  verbose_name='Статус задачи')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.command')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskArg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение атрибута')),
                ('arg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.commandarg')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Аргумент задачи',
                'verbose_name_plural': 'Аргументы задач',
                'db_table': 'tasks_args',
            },
        ),
    ]
