# Generated by Django 5.0.6 on 2024-06-30 06:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Серий номер телефона')),
                ('model', models.CharField(max_length=50, verbose_name='Модель телефона')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Пометки')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None,
                                                                         verbose_name='Номер телефона')),
                ('status',
                 models.CharField(choices=[('OFF', 'Выключен'), ('ON', 'Включен'), ('PROGRESS', 'Исполняет команду')],
                                  verbose_name='Статус номера телефона')),
                ('wa_is_business', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Номера телефонов',
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='PhoneLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_limits_from',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между сообщениями в рассылке от')),
                ('message_limits_to',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между сообщениями в рассылке до')),
                ('warming_message_limits_from',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между сообщениями в прогреве от')),
                ('warming_message_limits_to',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между сообщениями в прогреве до')),
                ('call_outgoing_limits_from',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между исходящими звонками от')),
                ('call_outgoing_limits_to',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между исходящими звонками до')),
                ('call_take_phone_limits_from',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между исходящими звонками от')),
                ('call_take_phone_limits_to',
                 models.SmallIntegerField(verbose_name='Диапазон пауз между исходящими звонками до')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.phone')),
            ],
            options={
                'verbose_name': 'Лимиты телефона',
                'verbose_name_plural': 'Лимиты телефонов',
                'db_table': 'phones_limits',
            },
        ),
    ]
