# Generated by Django 5.0.6 on 2024-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonelimit',
            name='call_outgoing_limits_from',
            field=models.SmallIntegerField(default=1, verbose_name='Диапазон пауз между исходящими звонками от'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='call_outgoing_limits_to',
            field=models.SmallIntegerField(default=3, verbose_name='Диапазон пауз между исходящими звонками до'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='call_take_phone_limits_from',
            field=models.SmallIntegerField(default=1, verbose_name='Диапазон пауз между исходящими звонками от'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='call_take_phone_limits_to',
            field=models.SmallIntegerField(default=3, verbose_name='Диапазон пауз между исходящими звонками до'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='message_limits_from',
            field=models.SmallIntegerField(default=1, verbose_name='Диапазон пауз между сообщениями в рассылке от'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='message_limits_to',
            field=models.SmallIntegerField(default=3, verbose_name='Диапазон пауз между сообщениями в рассылке до'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='warming_message_limits_from',
            field=models.SmallIntegerField(default=1, verbose_name='Диапазон пауз между сообщениями в прогреве от'),
        ),
        migrations.AlterField(
            model_name='phonelimit',
            name='warming_message_limits_to',
            field=models.SmallIntegerField(default=3, verbose_name='Диапазон пауз между сообщениями в прогреве до'),
        ),
    ]
