# Generated by Django 5.0.6 on 2024-06-30 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('phones', '0003_rename_call_outgoing_limits_from_phonelimit_call_outgoing_sec_sec_limits_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonelimit',
            old_name='call_outgoing_sec_sec_limits_from',
            new_name='call_outgoing_sec_limits_from',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='call_outgoing_sec_sec_limits_to',
            new_name='call_outgoing_sec_limits_to',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='call_take_phone_sec_sec_limits_from',
            new_name='call_take_phone_sec_limits_from',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='call_take_phone_sec_sec_limits_to',
            new_name='call_take_phone_sec_limits_to',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='message_sec_sec_limits_from',
            new_name='message_sec_limits_from',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='message_sec_sec_limits_to',
            new_name='message_sec_limits_to',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='warming_message_sec_sec_limits_from',
            new_name='warming_message_sec_limits_from',
        ),
        migrations.RenameField(
            model_name='phonelimit',
            old_name='warming_message_sec_sec_limits_to',
            new_name='warming_message_sec_limits_to',
        ),
    ]
